on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 1 * *'
name: tests
jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        node:
          - '12'
          - '14'
          - '15'
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Set git to turn off auto-converting line endings
        run: git config --global core.autocrlf false
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test -- --coverage=true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
