on:
  push:
  pull_request:
name: Test
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        node:
          - '18'
          - '20'
          - '22'
          - lts/*
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Set git to turn off auto-converting line endings
        run: git config --global core.autocrlf false
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test -- --coverage=true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
